/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
public class Calculator extends javax.swing.JFrame {

    double firstNumber;
    double secondNumber;
    double result;
    String operations;
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtDisplay = new javax.swing.JTextField();
        jBtn8 = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jBtnSub = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnEqu = new javax.swing.JButton();
        jBtnPlusMinus = new javax.swing.JButton();
        jBtnDec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 312, 47));

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 61));

        jBtnCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnCancel.setText("C");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 150, 61));

        jBtnSub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSub.setText("-");
        jBtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 70, 61));

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 70, 61));

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 61));

        jBtnBack.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnBack.setText("<");
        jBtnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 61));

        jBtnDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 70, 61));

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 61));

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 70, 61));

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 61));

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 70, 61));

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 61));

        jBtnMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 70, 61));

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 70, 61));

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 61));

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 70, 61));

        jBtnEqu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEqu.setText("=");
        jBtnEqu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEquActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 70, 61));

        jBtnPlusMinus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnPlusMinus.setText("+/-");
        jBtnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 70, 61));

        jBtnDec.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDec.setText(".");
        jBtnDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 70, 61));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn8.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn8.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        String backspace = null;
        if(jtxtDisplay.getText().length()>0){
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length()-1);
            backspace = strB.toString();
            jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn7.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn7.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn9.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn9.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
       String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn4.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn4.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn5.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn5.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn6.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn6.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn1.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn1.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn2.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn2.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn3.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn3.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        
        if("".equals(EnterNumber)){
            jtxtDisplay.setText(jBtn0.getText());
            
        }else
        {
            EnterNumber = jtxtDisplay.getText() + jBtn0.getText();
            jtxtDisplay.setText(EnterNumber);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecActionPerformed
        
        
        
        if(!jtxtDisplay.getText().contains(".")){
          jtxtDisplay.setText(jtxtDisplay.getText()+ jBtnDec.getText());  
        }
    }//GEN-LAST:event_jBtnDecActionPerformed

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jBtnDivActionPerformed

    private void jBtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubActionPerformed
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jBtnSubActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusMinusActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
        
        
    }//GEN-LAST:event_jBtnPlusMinusActionPerformed

    private void jBtnEquActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEquActionPerformed
        String answer ;
        secondNumber = Double.parseDouble(jtxtDisplay.getText());
        if("+".equals(operations)){
            result = firstNumber + secondNumber ;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }else if("-".equals(operations)){
            result = firstNumber - secondNumber ;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }else if("*".equals(operations)){
            result = firstNumber * secondNumber ;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }else if("/".equals(operations)){
            result = firstNumber / secondNumber ;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
            
        }
    }//GEN-LAST:event_jBtnEquActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        java.awt.EventQueue.invokeLater(() -> {
            new Calculator().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnDec;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnEqu;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnPlusMinus;
    private javax.swing.JButton jBtnSub;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
